branches:
  - configure-ci/core
language: csharp
solution: Exodus.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
  - dotnet restore Exodus.Core
  - dotnet build Exodus.Core
  - dotner restore Exodus.Tests
  - dotnet test Exodus.Tests
  - dotnet pack --no-restore --configuration Release Exodus.Core
  - dotnet nuget push Exodus.Core/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://www.nuget.org/api/v2/package