branches:
  - release/sql-server
language: csharp
solution: Exodus.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
  - dotnet test Exodus.Tests &&
    dotnet pack --configuration Release Exodus.SqlServer &&
    dotnet nuget push Exodus.SqlServer/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://www.nuget.org/api/v2/package