branches:
  - release/postgresql
language: csharp
solution: Exodus.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
  - dotnet test Exodus.Tests &&
    dotnet pack --configuration Release Exodus.Npgsql &&
    dotnet nuget push Exodus.Npgsql/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://www.nuget.org/api/v2/package