language: csharp
solution: Exodus.sln
matrix:
  include:
    - dotnet: 2.0.0
      mono: none
      dist: trusty
    - mono: latest
script:
  - dotnet restore
  - dotnet build
  - dotnet test Exodus.Tests
  - dotnet pack --no-restore --configuration Release Exodus.Core
  - nuget push Exodus.Core/bin/Release/*.nupkg -ApiKey $NUGET_API_KEY -Source https://www.nuget.org/api/v2/package
  - dotnet pack --no-restore --configuration Release Exodus.SqlServer
  - nuget push Exodus.SqlServer/bin/Release/*.nupkg -ApiKey $NUGET_API_KEY -Source https://www.nuget.org/api/v2/package