language: csharp
solution: Exodus.sln
mono: none
dotnet: 2.0.0
dist: trusty
install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg 
  - sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
  - sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-get install nuget
script:
  - dotnet restore
  - dotnet build
  - dotnet test Exodus.Tests
  - dotnet pack --no-restore --configuration Release Exodus.Core
  - nuget push Exodus.Core/bin/Release/*.nupkg -ApiKey $NUGET_API_KEY -Source https://www.nuget.org/api/v2/package -Verbosity detailed
  - dotnet pack --no-restore --configuration Release Exodus.SqlServer
  - nuget push Exodus.SqlServer/bin/Release/*.nupkg -ApiKey $NUGET_API_KEY -Source https://www.nuget.org/api/v2/package -Verbosity detailed